### PR TITLE
Add support for multiple offsets to time_offset module

### PR DESCRIPTION
**Pull request by sumkincpp**
Add support for multiple offsets to time_offset

```terraform
resource "time_offset" "example" {
  offset_years = 1
  offset_months = 1
}
output "one_year_and_month_from_now" {
  value = time_offset.example.rfc3339
}
```

Workaround right now, for example - use only one attribute, i.e. `offset_months=13`

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by SBGoods** [comment]
Hi @sumkincpp thank you for the contribution,
Since we currently allow practitioners to set multiple offsets in the configuration, there is a possibility that some practitioners may have these set inadvertently and this feature would result in a breaking change for them. We can consider this PR as part of a larger effort for a Time Provider major release in the future but we do not have a timeline for this at the moment. Feel free to keep this PR open if you would like, but we might not be able to review this PR in the near future.

**Comment by pascal-hofmann** [comment]
This provider has 3 resources and a major bug in one of them which cost me quite some time today. Why not just merge and release a new major version?

**Review by SBGoods — APPROVED** [review]
Hi @sumkincpp 
I've added a changelog entry and moved your doc example to the template to pass our CI check. Otherwise, this looks good to go.

Thank you for the contribution!

**Comment by pascal-hofmann** [comment]
Thanks for merging this! 🚀

**Pull request merged**
